
- import_tasks: addswap.yml

# Temporary workaround for outdated vagrant box base
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  become: yes

- name: install system tools
  yum:
    name: ['rsync', 'strace', 'nmap', 'yum-utils', 'sendmail',
           'nfs-utils', 'vim-enhanced', 'tmpwatch', 'ntpdate',
           'at', 'cronie-noanacron', 'ruby', 'mailx', 'crontabs',
           'logrotate', 'which', 'net-tools', 'lsof', 'screen',
           'mlocate']
  become: yes

- name: manage sendmail service
  service:
    name: sendmail
    state: started
    enabled: yes
  become: yes

- name: set up redmine user mail aliases
  lineinfile:
    dest: /etc/aliases
    regexp: "^{{ redmine_owner }}"
    line: "{{ redmine_owner }}: {{ redmine_mail_alias }}"
  become: yes
  notify: rebuild mail aliases

