---
- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - config.yml

  roles:
    - { role: rvm.ruby, tags: ruby, become: yes }
    - { role: rvm.ruby.patch, tags: ruby, become: yes }
    - { role: easyredmine, become: no }

  tasks:
